server:
  port: 8080

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

#  datasource:
#    url: jdbc:mysql://localhost:3308/user_registration
#    username: wso2carbon
#    password: wso2carbon
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: api-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: api-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
